### PR TITLE
add glide config and deps

### LINKED ISSUE #6: Add Glide Support
- [ ] Use glide for dependency management and commit deps to tree

### PR DESCRIPTION
**Pull request by rphillips**
Fixes #6

### CODE REVIEW

**Comment by itzg** [comment]
Is it possible to delay `glade install` until build time to avoid source controlling all of `vendor`. Apparently it might be possible https://github.com/Masterminds/glide#q-should-i-check-vendor-into-version-control

**Comment by rphillips** [comment]
AFAIK, there is not a way around it.

**Comment by rphillips** [comment]
I'll give it a shot

**Comment by itzg** [comment]
+1

**Pull request merged**
